### ISSUE TITLE
Days + Hours instead of just months

### ISSUE THREAD

**Issue by minsukchang** [kixlab/tv-dashboard#2]
It would be nice if it were days + hours instead of months

**Comment by graup** [comment]
I think it does do it automatically when it's less than 1 month, less than 1 day etc.

https://momentjs.com/docs/#/displaying/tonow/

**Comment by minsukchang** [comment]
aha! But 4 months seem like a long time away, where as 120days and 8 hours doesn't lol I feel like days+hours is a better enforcer.

**Comment by graup** [comment]
Good point. I'll change it to always display days + hours.

**Comment by graup** [comment]
Fixed in 01e3146cd24a1c114e0deee21934bf365366f34a
